# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

unsetopt AUTO_NAME_DIRS

if [[ -d "${HOME}/.zsh" ]]; then
  for file in $HOME/.zsh/*; do
    if [[ ! -d "${file}" ]]; then
      source "${file}"
    fi
  done
fi

autoload -U +X bashcompinit && bashcompinit
