#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

unsetopt AUTO_NAME_DIRS

if [[ -f ~/.eco_env ]]; then
  source ~/.eco_env
fi

if [[ -d "$HOME/.rc.d" ]]; then
    for file in $HOME/.rc.d/*; do
        source $file
    done
fi

# aliases stuff
if [[ -d "$HOME/.aliases.d" ]]; then
  for file in ~/.aliases.d/*; do
    source $file
  done
fi

